# Simple workflow for deploying static content to GitHub Pages
name: Build

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  HAXE_VERSION: 4.3.6
  SDK_VERSION: v0.24.1

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    #runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@v1.4.3
        with:
          packages: bash clang-15 lld-15 socat cmake meson pkg-config
          version: 1.0
          execute_install_scripts: true
      - name: Set env variables (Windows)
        if: runner.os == 'Windows'
        run: |
          echo "HAXELIB_PATH=C:/hostedtoolcache/windows/haxe/${{ env.HAXE_VERSION }}/x64/lib" | Out-File -FilePath $env:GITHUB_ENV -Append # no need for -Encoding utf8
      - name: Set env variables (Linux)
        if: runner.os == 'Linux'
        run: |
          echo "HAXELIB_PATH=/opt/hostedtoolcache/haxe/${{ env.HAXE_VERSION }}/x64/lib" >> $GITHUB_ENV
      - name: Setup Haxe environment
        uses: krdlab/setup-haxe@v1.5.1
        with:
          haxe-version: ${{ env.HAXE_VERSION }}
      - name: Install Haxe Dependencies
        run: |
          haxelib install haxe-concurrent 5.1.4
          haxelib install hscript 2.6.0
          haxelib install rulescript 0.2.0
          
          # Install HXCPP
          cd ${{ env.HAXELIB_PATH }}
          mkdir -p hxcpp
          cd hxcpp
          if [ ! -d "ps5-payload" ]; then
            git clone https://github.com/barisyild/hxcpp/ --branch ps5-payload ps5-payload
            echo ps5-payload > .current
            cd ps5-payload
          else
            cd ps5-payload
            git pull
          fi
          cd tools/hxcpp
          haxe compile.hxml
      - name: Install PS5 SDK
        run: |
          wget https://github.com/ps5-payload-dev/sdk/releases/download/v0.24.1/ps5-payload-sdk.zip
          sudo unzip -d /opt ps5-payload-sdk.zip
      - name: Build Payload
        run: |
          export PS5_PAYLOAD_SDK=/opt/ps5-payload-sdk
          haxe release.hxml --cmd "mv out/AirPSX out/airpsx.elf"
      - uses: actions/upload-artifact@v4
        with:
          name: airpsx.elf
          path: out/airpsx.elf